### ISSUE TITLE
Duplicate package name build warning

### ISSUE THREAD

**Issue by bubenheimer** [googlemaps/android-maps-ktx#135]
Building my app with the 2 dependencies below (using the current releases) causes build warnings. Please find a way to eliminate the warnings. Thanks.

#### Environment details

com.google.maps.android:maps-utils-ktx:3.0.0, com.google.maps.android:android-maps-utils:2.2.2

> Task :app:processFastDebugMainManifest
[com.google.maps.android:maps-utils-ktx:3.0.0] /Users/me/.gradle/caches/transforms-3/ff18f3a8e16af67bd303501ad035d84c/transformed/jetified-maps-utils-ktx-3.0.0/AndroidManifest.xml Warning:
	Package name 'com.google.maps.android' used in: com.google.maps.android:maps-utils-ktx:3.0.0, com.google.maps.android:android-maps-utils:2.2.2.

**Comment by arriolac** [comment]
Thanks for raising. From how I understand it, the fix should be to update the util library package name to a more specific package name to avoid this warning (e.g. `com.google.maps.android.utils`)

**Comment by arriolac** [comment]
@bubenheimer can you share your environment details (Android Studio version, Android Gradle Plugin version, etc.)

**Comment by bubenheimer** [comment]
Thanks, that sounds like an appropriate fix. I'm currently on AS Arctic Fox 7.0.0 Canary 14, AGP 7.0.0-alpha14, Gradle 7.0, Kotlin 1.5.0, but I think I saw this with older AGPs as well.

**Comment by arriolac** [comment]
@bubenheimer lmk if the latest version removed the warning for you

**Comment by bubenheimer** [comment]
It does, warning looks gone. Thank you kindly

**Comment by whhotw** [comment]
Well done.
