### ISSUE TITLE
Create a demo app which uses KTX features

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-ktx#2]

**Comment by barbeau** [comment]
MultiLayerDemoActivity is a good candidate for this - https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java

**Comment by barbeau** [comment]
@arriolac What package name do you want to use for this demo app?  This library is `com.google.maps.android.ktx`. Do you want to use `com.google.maps.android.ktx.demo`?

FWIW, the Java package names for the library and demo apps are `com.google.maps.android` and `com.google.maps.android.utils.demo`, respectively.

**Comment by arriolac** [comment]
`com.google.maps.android.ktx.demo` makes sense to me 👍
