### ISSUE TITLE
How to get current location and change base tiles map to satellite  

### ISSUE THREAD

**Issue by awangsoftware** [googlemaps/android-maps-ktx#45]
Can u make demo library for How to get current location and change base tiles map to satellite

**Comment by arriolac** [comment]
[MyLocationDemoActivity](https://github.com/googlemaps/android-samples/blob/master/ApiDemos/java/app/src/main/java/com/example/mapdemo/MyLocationDemoActivity.java) shows you how to get the device's current location. This demo is only in Java for now and has yet to be translated to Kotlin (contributions are welcome!).

For changing map types, see [Change the map type](https://developers.google.com/maps/documentation/android-sdk/map#change_the_map_type) portion of the docs.

Hope this helps!
