### ISSUE TITLE
android-maps-ktx: Listeners aren't removed in awaitClose block in cameraEvents(): Flow implementation

### ISSUE THREAD

**Issue by ychescale9** [googlemaps/android-maps-ktx#80]
👋  I was looking at the new `cameraEvents(): Flow<CameraEvent>` implementation. It looks like the [listeners aren't cleared when the channel is closed / cancelled](https://github.com/googlemaps/android-maps-ktx/blob/bd2508d6cc69cbfc3371fca4ae3b7e0c546df68f/maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt#L68-L73). I'd expect something like this:

```kotlin
callbackFlow {
  val idleListener = GoogleMap.OnCameraIdleListener {
    offer(CameraIdleEvent)
  }
  ...
  setOnCameraIdleListener(idleListener)
  awaitClose {
    setOnCameraIdleListener(null)
    ...
  }
}
```

Happy to send a PR 😃 .

**Comment by arriolac** [comment]
Thanks for filing. Feel free to send us a PR!
