### ISSUE TITLE
Offer can throw, crashing the app on edge cases where cancellation happens in another thread

### ISSUE THREAD

**Issue by LouisCAD** [googlemaps/android-maps-ktx#85]
https://github.com/googlemaps/android-maps-ktx/blob/ba78a13ab92b2e60d2da02f62d9ad2c2be6ff4e3/maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt#L69-L72

Relevant issue with workaround that this library can use (with `internal` visibility): https://github.com/Kotlin/kotlinx.coroutines/issues/974

**Comment by arriolac** [comment]
Thanks for raising this @LouisCAD
