### ISSUE TITLE
Any reason we don't have a sample for the v3 SDK?

### ISSUE THREAD

**Issue by LouisCAD** [googlemaps/android-maps-ktx#88]
If there is none, it'd be great to have one here.

**Comment by arriolac** [comment]
Definitely something that can be added. A similar strategy can be done using the [copyGmsToV3Beta](https://github.com/googlemaps/android-maps-ktx/blob/main/build.gradle#L230...L236) Gradle task.

**Comment by LouisCAD** [comment]
Come on dear bot, there's only 6 open issues! 😄

**Comment by LouisCAD** [comment]
Will this issue ever be addressed?

**Comment by arriolac** [comment]
Unfortunately I do not have the bandwidth to address this at the moment. V3 and non-V3 KTX extensions are essentially the same, and so would the samples, with the exception of imports. Contributor help is certainly welcome here.

**Comment by barbeau** [comment]
Product flavors can be used for this, similar to the implementation for android-maps-utils demo app in PR https://github.com/googlemaps/android-maps-utils/pull/811.
