### ISSUE TITLE
Typo in Repository description.

### ISSUE THREAD

**Issue by fumiya-kume** [googlemaps/android-maps-ktx#9]
Sorry simple issues.

I found typo at Repository description.

> Kotin extensions (KTX)

I think better than ‘Kotlin extensions’

**Comment by barbeau** [comment]
Thanks @fumiya-kume!

@arriolac Looks like I don't have access to change this - it's in the main repo description:

![image](https://user-images.githubusercontent.com/928045/76233290-5d1d2500-61fe-11ea-87e7-db6f04407af3.png)

**Comment by arriolac** [comment]
Fixed! Thanks for reporting
