### ISSUE TITLE
awaitMap can prevent cancellation forever, triggering memory leaks or suspending deadlocks

### ISSUE THREAD

**Issue by LouisCAD** [googlemaps/android-maps-ktx#90]
The `awaitMap()` extension function for `SupportMapFragment` uses the non cancellable `suspendCoroutine` function from the `kotlin.coroutines` package, so if the map is never shown, it'll never resume, even if cancelled.

The solution is to use `suspendCancellationCoroutine` from the `kotlinx.coroutines` package, even if there's no way to unregister the underlying callback in the current Google Maps API for Android.

It's better than what we have now because in the first case, the leaked objects can reach well beyond the `SupportMapFragment`, while in the second case, we only have a temporary leak (until the callback finally gets called, for example after the map is shown, or once the `SupportMapFragment` gets garbage collected).

**Comment by arriolac** [comment]
Thanks for filing. I'll take a look at this.

**Comment by enriquebautista** [comment]
@LouisCAD @arriolac does this scenario also apply to MapView? 
https://github.com/googlemaps/android-maps-ktx/blob/main/maps-ktx/src/main/java/com/google/maps/android/ktx/MapView.kt
