### ISSUE TITLE
SDK v3 is not properly using AndroidX as it still depends on support library dependencies

### ISSUE THREAD

**Issue by LouisCAD** [googlemaps/android-maps-ktx#93]
The following appears when running `./gradlew :some-module:dependencies` on a module that depends on the Google Maps SDK for Android v3 (3.1.0-beta):

![EhB1Bs3VgAAZygJ](https://user-images.githubusercontent.com/6975237/92567542-20e68200-f27e-11ea-8f68-330511094a08.png)

That means many apps pay a high build time price because they need to keep jetifier because of Google Maps still not being properly migrated as it depends on support libraries instead of AndroidX.

Please, make fixing this a top priority, it affects developers in the wild, not even counting the quiet ones: https://twitter.com/chris_h_codes/status/1300985936377868289?s=20

**Comment by LouisCAD** [comment]
For reference this half-complete AndroidX migration triggers this warning at build time and Gradle sync time:
```
[Processor] Library '/Users/me/.gradle/caches/modules-2/files-2.1/com.google.android.libraries.maps/maps/3.1.0-beta/78bbce6fcebb76eef9c0fb4dec218768961cf5d0/maps-3.1.0-beta.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
```

**Comment by NitroG42** [comment]
Is there any news on the subject ? I think it is also using Jcenter dependencies which can be workarounded but is not ideal.
Is this the right place for this issue or is there a more direct tracker for Google Maps SDK V3.0 ?

**Comment by barbeau** [comment]
The Maps SDK v3 beta was deprecated on August 18th and will be fully decommissioned in late 2022 - more here:
https://developers.google.com/maps/documentation/android-sdk/releases#2021-08-18

So I think it's doubtful that this issue will be fixed.

The best place to report bugs directly for the Maps SDK is the Google issue tracker - specifically, for Maps SDK v3 beta:
https://issuetracker.google.com/issues/new?component=541018&template=1201436

**Comment by barbeau** [comment]
Actually, looking back at the original Twitter thread linked in the first comment, looks like there is already an issue open for this:
https://issuetracker.google.com/issues/161912064

**Comment by barbeau** [comment]
I'm going to close out this issue since it's not an issue with android-maps-ktx but instead with the Maps SDK v3 beta library - I'd encourage anyone interested in providing feedback to follow/comment on the [above Google issue tracker issue](https://issuetracker.google.com/issues/161912064).

**Comment by LouisCAD** [comment]
12 months for a link to an unresolved P4 issue for a closed source library we can't simply fork… 😐

I stay hopeful, but you certainly agree it takes a lot of willpower to stay so.

**Comment by NitroG42** [comment]
I understand why I missed that (I checked the releases notes page in the beginning of the week and there was no mention of the deprecation) -> This notice is not displayed with others languages -> https://developers.google.com/maps/documentation/android-sdk/beta-releases?hl=fr (see how the menu differs on the left)
Thanks for your answers, I hope a new version will be available soon then !
