### ISSUE TITLE
Changelog is not updated

### ISSUE THREAD

**Issue by danielgomezrico** [googlemaps/android-maps-ktx#96]
Hi

I see that the last release is 2.x but the change log does not reflects that https://github.com/googlemaps/android-maps-ktx/blob/main/CHANGELOG.md.

How can we know what was deployed?

**Comment by arriolac** [comment]
The specific GitHub release in https://github.com/googlemaps/android-maps-ktx/releases should give you the most detailed information on what's changed. I need to remove the `CHANGELOG.md` to avoid confusion.
